### ISSUE TITLE
Pass delay time as an argument.

### ISSUE THREAD

**Issue by aniketpanjwani** [miheerdew/delayed-admin#4]
Hi Miheer,

Cool project you have here. I'm considering using delayed-admin for an internet blocking software I'm developing for Linux. However, it would be useful if delay time could be passed as an argument to delayed. Would you consider merging in a pull request in which I implemented this feature?

Cheers,

Aniket

**Comment by miheerdew** [comment]
Thanks Aniket, but wouldn't passing a delay with the `sudo delayed` allow admins to do `sudo delayed 0` and instantly get admin access? That would defeat the purpose of `delayed admin`. 

For your script, perhaps you can manually write the  delay in `/etc/delayed-admin.conf` file everytime?

**Comment by miheerdew** [comment]
Do you need a command which locks out administrator access for specific amount of time?  One could use the `at` command for that.

**Comment by aniketpanjwani** [comment]
Yes, that's a good point. I guess the issue is that if you called "sudo delayed 1200" in one terminal, if you got impatient, you could open another terminal and call "sudo delayed 0". In order for this to work, delayed-admin would need some way of knowing whether some other "sudo delayed" call is in progress.

**Comment by miheerdew** [comment]
I am in the process of coding this idea. Tell me if this solves your problem.

So the usage will be
- Step 1 : Install delayed-admin with `sudo setup.sh install`
- Step 2: Change `/etc/delayed-admin.conf` to a large value (say `9000`). This will only play the role of a backdoor if things go wrong.
- Step 3: Let's call the script below `abdicate.sh`. Run it as `sudo abdicate.sh 1200` and it makes you into a regular user for 1200 seconds, and regains `sudo` privileges afterwards.

## abdicate.sh      
Here is the pseudo-code for abdicate.sh

```
#!/bin/bash

set -e

TIME="$1"
USER="$SUDO_USER"
ADMIN_GROUP="sudo"

add_user_to_group $USER delayed-admin
remove_user_from_group $USER $ADMIN_GROUP

### Alternative 1
# sleep $TIME
# add_user_to_group $USER $ADMIN_GROUP

### Alternative 2 (better if I can get this to work)
at "now+$((TIME/60))min" <<_EOF
   add_user_to_group $USER $ADMIN_GROUP
_EOF
```

**Comment by aniketpanjwani** [comment]
One issue with this script is that removing the user from the admin group may only take effect for new terminals. So, I wonder what would happen if

1. You run abdicate.sh, and then during the SLEEP, you kill the script. In the same terminal in which you called the script, I think you will be able to use sudo.
2. You run abdicate.sh, and during the sleep, you try to change users' groups through Linux Mint/Ubuntu's GUI interface. You should need sudo permissions to get into these GUI programs, but I think that you will be able to get into the programs, because changes to sudo group membership might not propagate until you log out and log back in.

**Comment by aniketpanjwani** [comment]
Here's a link to a script I wrote with help from a freelancer: https://gist.github.com/aniketpanjwani/109bac507d230ef1fe18027b4b79e5d6 .

It effectively implements abdicate.sh, and it solves problem 1 by backgrounding the second half of the script using nohup. The only problem is that problem 2 is not solved: I can still change users' groups through Linux Mint GUI interface. Unless, I can find a way to propagate the change in sudo group membership without logging in/logging out, this approach won't really work.

So, the best approach may be delayed-admin's current approach, in which the current user is not part of the sudo group, but is part of the delayed-admin group. However, the delayed-admin program would need to somehow carry state, so that if you call "sudo delayed 1200", then you cannot call "sudo delayed 0" from elsewhere.

Looking forward to hearing your thoughts on the above!

**Comment by miheerdew** [comment]
Can you confirm that once a user is removed from the sudo group, he can still run sudo (either in the same shell or through gui) until he logs out? This doesn't seem to be the behavior on mac for me. 
To check this you may follow the instructions [here](https://www.ostechnix.com/delayed-admin-temporarily-drop-admin-privileges-administrators/) and let me know if you need to log out or not. 

Thanks!

**Comment by miheerdew** [comment]
Can confirm that 1 and 2 don't happen on mac.

**Comment by miheerdew** [comment]
Hi Aniket, try out `abdicate.sh` script from the [new branch](https://github.com/miheerdew/delayed-admin/tree/abdicate). Right now it uses sleep, but I would like to use `at` (so that computer doesn't have to be awake all the time).

**Comment by aniketpanjwani** [comment]
I can confirm that the user can still run sudo until he logs out on Linux Mint 18. Specifically, I did the following:

1. Created a new administrator user called test_user.
2. Logged in as test_user.
3. Cloned the git repository.
4. Changed directory to the git repository.
5. Ran sudo ./setup.sh install.
6. Ran sudo ./abdicate.sh 60.
7. Clicked on "Users and Groups" through menu, and received prompt for my password.
8. Entered my password, and successfully opened the program.
9. Clicked on test_user's icon, and saw that test_user was part of the delayed_admin group, and not part of the sudo group.

So, I think it really is the case that changes to sudo group only take effect after logging in/out. Here's one possible way to move forward. When you run sudo ./abdicate.sh 60, the following happens:

1. An entry is added to root's crontab which restores the current user's sudo group membership either in 60 seconds or the next login.
2. The user is automatically logged out.

It's definitely an inconvenient way of doing things, but the only thing I can think of if logging out is required. [Here](https://serverfault.com/questions/98900/is-a-reboot-required-to-refresh-permissions-after-adding-a-user-to-a-new-group)'s a ServerFault question which might be relevant.

**Comment by miheerdew** [comment]
Thanks for confirming this and for the solution. I agree with your solution, but perhaps it is better to use `at` instead of  `cron` because this is a one time job.

**Comment by miheerdew** [comment]
Hi Aniket, I have implemented it using `at` now. Can you test if it works on linux? The latest code is on the abdicate branch.

I just print a message recommending the user to log off rather than forcefully logging the user out.

**Comment by aniketpanjwani** [comment]
For sure - will check it out tomorrow or Monday!

**Comment by aniketpanjwani** [comment]
Hey miheer - sorry about the delay. Will get to it this weekend

**Comment by miheerdew** [comment]
No worries! I used this opportunity to set up some automatic testing using travis-CI, so thing should most probably work. I also also have more instructions on the Readme page. Preparing all of that in #6.
