### ISSUE TITLE
On Fedora/CentOS, ADMIN_GROUP should be "wheel"

### ISSUE THREAD

**Issue by yamrzou** [miheerdew/delayed-admin#7]
Hi,

Thank you for writing this tool.

I'm using Fedora, and when I run `sudo ./abdicate.sh "now + 1 hour"`, I get:
```
[✔] atd is already running.
warning: commands will be executed using /bin/sh
job 4 at Sun May 10 11:19:00 2020
[✔] Scheduled: Add yamrzou to sudo group at now + 1 hour
[✔] Added yamrzou to the delayed-admin group
gpasswd: group 'sudo' does not exist in /etc/group
[❌] Removed yamrzou from sudo group
```

According to [Fedora Docs](https://docs.fedoraproject.org/en-US/quick-docs/adding_user_to_sudoers_file/), the sudoers group is `wheel`.

Also, the command `sudo ./abdicate.sh "now+2hr"` from the Readme doesn't seem to work, I'm getting:
```
[✔] atd is already running.
syntax error. Last token seen: h
Garbled time
[❌] Scheduled: Add yamrzou to sudo group at now+2hr
```

**Comment by miheerdew** [comment]
Thanks for your response. This is perhaps due to differences in the OS platform. 
Unfortunately, I don't have access to Fedora. If you wish to work on this, I am happy to help you with a Pull Request.
