### ISSUE TITLE
Abdicate doesn't work: "garbled time"

### ISSUE THREAD

**Issue by alienbogart** [miheerdew/delayed-admin#9]
The command `sudo ./abdicate.sh "now+2hr"` (actually `sudo delayed ./abdicate.sh "now+2hr"` because `sudo` is correctly blocked by the program) has the following output:

```
Sleeping for 30 seconds starting from 12/22/20 04:27:10
Running command './abdicate.sh now+2hr'
[✔] atd is already running.
syntax error. Last token seen: h
Garbled time
[❌] Scheduled: Add my-username to sudo group at now+2hr
```

And doesn't work.

**Comment by miheerdew** [comment]
Hi, please see `man at` for the notation to use to schedule jobs at a specific time. It might be different from `now+2hr`.
